version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/aws-codebuild-samples

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
hooks:
  ApplicationStop:
    - location: deploy_scripts/stop.sh
      runas: root
  ApplicationStart:
    - location: deploy_scripts/start.sh
      runas: root
  ValidateService:
    - location: deploy_scripts/validate.sh
      runas: root
